# Generated by Django 6.0.6 on 2026-08-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('enroll_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
