# Generated by Django 6.0.6 on 2026-08-19 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='teachers',
            new_name='students',
        ),
    ]
