# Generated by Django 6.0.6 on 2026-08-19 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_teachers_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='enroll_date',
        ),
    ]
