# Generated by Django 6.0.6 on 2026-08-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_students_enroll_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='Mob_no',
            field=models.IntegerField(default=6266912811),
            preserve_default=False,
        ),
    ]
