# Generated by Django 6.0.6 on 2026-09-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_files',
            name='document',
            field=models.FileField(default='doc', upload_to='documents/'),
            preserve_default=False,
        ),
    ]
