# Generated by Django 6.0.6 on 2026-09-19 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_upload_files_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload_files',
            name='document',
        ),
    ]
