# Generated by Django 6.0.6 on 2026-09-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_upload_files_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload_files',
            name='image',
        ),
        migrations.AddField(
            model_name='upload_files',
            name='document',
            field=models.FileField(default='document', upload_to='documents/'),
            preserve_default=False,
        ),
    ]
