# Generated by Django 6.0.6 on 2026-09-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_upload_files_image_upload_files_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload_files',
            name='document',
        ),
        migrations.AddField(
            model_name='upload_files',
            name='image',
            field=models.ImageField(default='img', upload_to='images/'),
            preserve_default=False,
        ),
    ]
