# Generated by Django 6.0.6 on 2026-09-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_student_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mob',
            field=models.IntegerField(default=6266912811),
            preserve_default=False,
        ),
    ]
